spring.application.name=StudentApplication

#database Configuration
spring.datasource.url=jdbc:mysql://localhost:3306/studentdb
spring.datasource.name=root
spring.datasource.password= root

#jpa Configuration

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true